version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - rest-api
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/.next

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: skillshare
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  migrate:
    build:
      context: .
      dockerfile: shared/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./shared/.env
    volumes:
      - ./shared/prisma:/app/prisma

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    depends_on:
      - postgres
      - migrate
    env_file:
      - ./task-service/.env
    volumes:
      - ./shared/proto:/shared/proto
      - ./shared/prisma:/shared/prisma
    ports:
      - "4000:4000"

  rest-api:
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    depends_on:
      - postgres
      - migrate
      - task-service
    env_file:
      - ./rest-api/.env
    volumes:
      - ./shared/proto:/shared/proto
      - ./shared/prisma:/shared/prisma
    ports:
      - "5000:5000"

volumes:
  pgdata:
