version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - rest-api
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://rest-api:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: skillshare
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  migrate:
    build:
      context: .
      dockerfile: shared/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@123@postgres:5432/skillshare
    volumes:
      - ./shared/prisma:/app/prisma

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    depends_on:
      - postgres
      - migrate
    environment:
      PORT: 4000
      DATABASE_URL: postgres://admin:admin@123@postgres:5432/skillshare
      TASK_GRPC_PROTO: /shared/proto/
    volumes:
      - ./shared/proto:/shared/proto
      - ./shared/prisma:/shared/prisma
    ports:
      - "4000:4000"

  rest-api:
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    depends_on:
      - postgres
      - migrate
      - task-service
    environment:
      PORT: 5000
      DATABASE_URL: postgres://admin:admin@123@postgres:5432/skillshare
      TASK_GRPC_PROTO: /shared/proto/
      TASK_SERVICE_URI: task-service:4000
    volumes:
      - ./shared/proto:/shared/proto
      - ./shared/prisma:/shared/prisma
    ports:
      - "5000:5000"

volumes:
  pgdata:
